[package]
name = "web_server_practice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
serde = "1.0.152"
log = "0.4.17"
env_logger = "0.10.0"
mongodb = "2.3.1"
redis = "0.22.2"
serde_json = "1.0.91"
tokio = "1.24.1"
bcrypt = "0.13.0"
